// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psicomy.Services.Billing.Data;

#nullable disable

namespace Psicomy.Services.Billing.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260302180000_AddPaymentMethodType")]
    partial class AddPaymentMethodType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // PaymentMethodType added to PaymentInvoice entity
            // Full model in BillingDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
