// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psicomy.Services.Billing.Data;

#nullable disable

namespace Psicomy.Services.Billing.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260302170000_AddSentTrialReminders")]
    partial class AddSentTrialReminders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Psicomy.Services.Billing.Models.SentTrialReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MilestoneDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "MilestoneDay")
                        .IsUnique();

                    b.ToTable("SentTrialReminders", (string)null);
                });

            // All other entities remain unchanged from previous migration snapshot
            // (PaymentInvoice, PaymentPlan, ProcessedStripeEvent, StudentVerification, TenantLicense)
            // Omitted for brevity - full model in BillingDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
